package de.bierverein.api;

import org.springframework.http.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.Authentication;
import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;import org.springframework.web.server.ResponseStatusException;
import java.time.*;import java.util.*;

@RestController @RequestMapping("/api/device-planning")
@PreAuthorize("@devicePermissionGuard.allowed(authentication, 'read')")
public class DeviceInspectionPlanningController {
 private final DeviceRepository devices;private final DeviceLocationRepository locations;private final TrainingScheduleEventRepository events;private final DeviceInspectionTaskRepository tasks;
 public DeviceInspectionPlanningController(DeviceRepository d,DeviceLocationRepository l,TrainingScheduleEventRepository e,DeviceInspectionTaskRepository t){devices=d;locations=l;events=e;tasks=t;}

 @GetMapping("/locations") public List<LocationDto> locations(){
  Map<String,DeviceLocation> saved=new TreeMap<>(String.CASE_INSENSITIVE_ORDER);locations.findByActiveTrueOrderByNameAsc().forEach(x->saved.put(x.getName(),x));
  devices.findByActiveTrueOrderByNameAsc().stream().map(Device::getLocation).filter(Objects::nonNull).filter(x->!x.isBlank()).forEach(n->saved.computeIfAbsent(n,k->{DeviceLocation x=new DeviceLocation();x.setName(k);return x;}));
  return saved.values().stream().map(x->new LocationDto(x.getId(),x.getName(),x.isFireRelevant(),x.isActive())).toList();
 }
 @PostMapping("/locations") @PreAuthorize("@devicePermissionGuard.allowed(authentication, 'write')") public LocationDto saveLocation(@RequestBody LocationRequest r){
  if(r==null||r.name()==null||r.name().isBlank())throw bad("Standortname ist erforderlich.");DeviceLocation x=r.id()==null?locations.findByNameIgnoreCase(r.name().trim()).orElseGet(DeviceLocation::new):locations.findById(r.id()).orElseThrow(()->notFound("Standort nicht gefunden."));
  x.setName(r.name().trim());x.setFireRelevant(Boolean.TRUE.equals(r.fireRelevant()));x.setActive(true);x=locations.save(x);return new LocationDto(x.getId(),x.getName(),x.isFireRelevant(),x.isActive());
 }
 @DeleteMapping("/locations/{id}") @PreAuthorize("@devicePermissionGuard.allowed(authentication, 'delete')")
 public ResponseEntity<Void> deleteLocation(@PathVariable Long id){DeviceLocation x=locations.findById(id).orElseThrow(()->notFound("Standort nicht gefunden."));if(devices.findByActiveTrueOrderByNameAsc().stream().anyMatch(d->x.getName().equalsIgnoreCase(d.getLocation()==null?"":d.getLocation())))throw new ResponseStatusException(HttpStatus.CONFLICT,"Standort wird von Geräten verwendet. Bitte zuerst die Geräte umordnen.");x.setActive(false);locations.save(x);return ResponseEntity.noContent().build();}
 @GetMapping("/sessions") public List<SessionDto> sessions(){LocalDate from=LocalDate.now().minusMonths(2),to=LocalDate.now().plusYears(1);List<SessionDto> out=new ArrayList<>();for(TrainingScheduleEvent e:events.findByActiveTrueAndStartDateLessThanEqualAndEndDateGreaterThanEqualOrderByStartDateAsc(to,from)){if(!e.isDeviceInspection())continue;for(LocalDate d=e.getStartDate().isAfter(from)?e.getStartDate():from;!d.isAfter(e.getEndDate().isBefore(to)?e.getEndDate():to);d=d.plusDays(1))if(occurs(e,d)){List<DeviceInspectionTask> ts=tasks.findByEventIdAndOccurrenceDateOrderByDeviceNameAsc(e.getId(),d).stream().filter(t->t.getDevice().isInspectionRequired()).toList();out.add(new SessionDto(e.getId(),d,e.getTitle(),split(e.getDeviceLocations()),split(e.getDeviceCategories()),ts.size(),(int)ts.stream().filter(t->!"PENDING".equals(t.getStatus())).count()));}}return out.stream().sorted(Comparator.comparing(SessionDto::date)).toList();}
 @GetMapping("/sessions/{eventId}/{date}") @Transactional public SessionDetail session(@PathVariable Long eventId,@PathVariable LocalDate date){TrainingScheduleEvent e=event(eventId);if(!e.isDeviceInspection()||!occurs(e,date))throw bad("Ungültiger Geräteprüftermin.");ensureTasks(e,date);return new SessionDetail(new SessionDto(e.getId(),date,e.getTitle(),split(e.getDeviceLocations()),split(e.getDeviceCategories()),0,0),tasks.findByEventIdAndOccurrenceDateOrderByDeviceNameAsc(eventId,date).stream().filter(t->t.getDevice().isInspectionRequired()).map(this::taskDto).toList());}
 @PutMapping("/tasks/{id}") @Transactional @PreAuthorize("@devicePermissionGuard.allowed(authentication, 'write')") public TaskDto updateTask(@PathVariable Long id,@RequestBody TaskRequest r,Authentication auth){DeviceInspectionTask t=tasks.findById(id).orElseThrow(()->notFound("Prüfposition nicht gefunden."));String s=r.status()==null?"":r.status().toUpperCase();if(!Set.of("PENDING","INSPECTED","NOT_INSPECTABLE","DEFECTIVE").contains(s))throw bad("Ungültiger Prüfstatus.");t.setStatus(s);t.setNote(clean(r.note()));t.setUpdatedAt(Instant.now());t.setUpdatedBy(auth.getName());Device d=t.getDevice();d.setOperationalStatus(s.equals("DEFECTIVE")?"DEFECTIVE":s.equals("NOT_INSPECTABLE")?"NOT_INSPECTABLE":"OK");d.setOperationalStatusAt(Instant.now());d.setOperationalStatusNote(t.getNote());devices.save(d);return taskDto(tasks.save(t));}
 @PostMapping("/devices/{id}/repaired") @PreAuthorize("@devicePermissionGuard.allowed(authentication, 'write')") public void repaired(@PathVariable Long id){Device d=devices.findById(id).orElseThrow(()->notFound("Gerät nicht gefunden."));d.setOperationalStatus("OK");d.setOperationalStatusAt(Instant.now());d.setOperationalStatusNote("Als repariert gemeldet");devices.save(d);}
 @GetMapping("/alerts") @PreAuthorize("isAuthenticated()") public List<AlertDto> alerts(){Set<String> relevant=new TreeSet<>(String.CASE_INSENSITIVE_ORDER);locations.findByActiveTrueOrderByNameAsc().stream().filter(DeviceLocation::isFireRelevant).map(DeviceLocation::getName).forEach(relevant::add);return devices.findByActiveTrueOrderByNameAsc().stream().filter(d->Set.of("DEFECTIVE","IN_REPAIR").contains(d.getOperationalStatus())&&(d.getCompartment()!=null&&d.getCompartment().getVehicle().isFireRelevant()||d.getLocation()!=null&&relevant.contains(d.getLocation()))).map(d->new AlertDto(d.getId(),d.getName(),displayLocation(d),d.getOperationalStatusNote(),d.getOperationalStatus())).toList();}
 @GetMapping("/summary") public Summary summary(){List<Device> all=devices.findByActiveTrueOrderByNameAsc();return new Summary((int)all.stream().filter(d->"DEFECTIVE".equals(d.getOperationalStatus())).count(),(int)all.stream().filter(d->"NOT_INSPECTABLE".equals(d.getOperationalStatus())).count());}
 private void ensureTasks(TrainingScheduleEvent e,LocalDate date){Set<String> ls=new HashSet<>(split(e.getDeviceLocations())),cs=new HashSet<>(split(e.getDeviceCategories()));Set<Long> existing=new HashSet<>();tasks.findByEventIdAndOccurrenceDateOrderByDeviceNameAsc(e.getId(),date).forEach(t->existing.add(t.getDevice().getId()));for(Device d:devices.findByActiveTrueOrderByNameAsc())if(d.isInspectionRequired()&&ls.contains(deviceLocation(d))&&cs.contains(d.getCategory())&&!existing.contains(d.getId())){DeviceInspectionTask t=new DeviceInspectionTask();t.setEventId(e.getId());t.setOccurrenceDate(date);t.setDevice(d);tasks.save(t);}}
 private String deviceLocation(Device d){return d.getCompartment()!=null?d.getCompartment().getVehicle().getName():d.getLocation();}
 private String displayLocation(Device d){return d.getCompartment()!=null?d.getCompartment().getVehicle().getName()+" / "+d.getCompartment().getName():d.getLocation();}
 private boolean occurs(TrainingScheduleEvent e,LocalDate d){return !d.isBefore(e.getStartDate())&&!d.isAfter(e.getEndDate())&&(!e.isRecurring()?d.equals(e.getStartDate()):split(e.getWeekdays()).contains(d.getDayOfWeek().name())&&(!e.isLastWeekdayOfMonth()||d.plusWeeks(1).getMonth()!=d.getMonth()));}
 private TrainingScheduleEvent event(Long id){return events.findById(id).orElseThrow(()->notFound("Termin nicht gefunden."));}private List<String> split(String s){return s==null||s.isBlank()?List.of():Arrays.stream(s.split(",")).map(String::trim).filter(x->!x.isBlank()).toList();}
 private TaskDto taskDto(DeviceInspectionTask t){Device d=t.getDevice();return new TaskDto(t.getId(),d.getId(),d.getName(),d.getInventoryNumber(),displayLocation(d),d.getCategory(),t.getStatus(),t.getNote(),t.getUpdatedBy(),t.getUpdatedAt());}private String clean(String x){return x==null||x.isBlank()?null:x.trim();}
 private ResponseStatusException bad(String x){return new ResponseStatusException(HttpStatus.BAD_REQUEST,x);}private ResponseStatusException notFound(String x){return new ResponseStatusException(HttpStatus.NOT_FOUND,x);}
 public record LocationRequest(Long id,String name,Boolean fireRelevant){} public record LocationDto(Long id,String name,boolean fireRelevant,boolean active){}
 public record SessionDto(Long eventId,LocalDate date,String title,List<String> locations,List<String> categories,int total,int completed){} public record SessionDetail(SessionDto session,List<TaskDto> tasks){}
 public record TaskRequest(String status,String note){} public record TaskDto(Long id,Long deviceId,String deviceName,String inventoryNumber,String location,String category,String status,String note,String updatedBy,Instant updatedAt){}
 public record AlertDto(Long deviceId,String deviceName,String location,String note,String status){} public record Summary(int defective,int notInspectable){}
}
