package de.bierverein.api;

import org.springframework.http.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;import org.springframework.web.server.ResponseStatusException;
import java.util.*;

@RestController @RequestMapping("/api/vehicles")
public class FireVehicleController {
 private static final Set<String> AREAS=Set.of("DRIVER","PASSENGER","CREW","ROOF","REAR","FRONT");
 private final FireVehicleRepository vehicles;private final VehicleCompartmentRepository compartments;private final DeviceRepository devices;
 public FireVehicleController(FireVehicleRepository v,VehicleCompartmentRepository c,DeviceRepository d){vehicles=v;compartments=c;devices=d;}
 @GetMapping @PreAuthorize("@vehiclePermissionGuard.allowed(authentication,'read')") @Transactional(readOnly=true)
 public List<VehicleDto> all(){return vehicles.findByActiveTrueOrderByNameAsc().stream().map(this::dto).toList();}
 @PostMapping @PreAuthorize("@vehiclePermissionGuard.allowed(authentication,'write')") public VehicleDto create(@RequestBody VehicleRequest r){if(r==null||r.name()==null||r.name().isBlank())throw bad("Fahrzeugname ist erforderlich.");FireVehicle v=new FireVehicle();v.setName(trim(r.name(),120));v.setCallSign(trim(r.callSign(),40));v.setNotes(trim(r.notes(),1000));v.setFireRelevant(!Boolean.FALSE.equals(r.fireRelevant()));return dto(vehicles.save(v));}
 @PutMapping("/{id}") @PreAuthorize("@vehiclePermissionGuard.allowed(authentication,'write')") public VehicleDto update(@PathVariable Long id,@RequestBody VehicleRequest r){FireVehicle v=find(id);if(r.name()==null||r.name().isBlank())throw bad("Fahrzeugname ist erforderlich.");v.setName(trim(r.name(),120));v.setCallSign(trim(r.callSign(),40));v.setNotes(trim(r.notes(),1000));if(r.fireRelevant()!=null)v.setFireRelevant(r.fireRelevant());return dto(vehicles.save(v));}
 @PostMapping("/{id}/compartments") @PreAuthorize("@vehiclePermissionGuard.allowed(authentication,'write')") public CompartmentDto compartment(@PathVariable Long id,@RequestBody CompartmentRequest r){FireVehicle v=find(id);VehicleCompartment c=new VehicleCompartment();c.setVehicle(v);apply(c,r);return compartmentDto(compartments.save(c));}
 @PutMapping("/compartments/{id}") @PreAuthorize("@vehiclePermissionGuard.allowed(authentication,'write')") public CompartmentDto updateCompartment(@PathVariable Long id,@RequestBody CompartmentRequest r){VehicleCompartment c=compartments.findById(id).orElseThrow(()->notFound("Fach nicht gefunden."));apply(c,r);return compartmentDto(compartments.save(c));}
 @PutMapping("/compartments/{id}/device/{deviceId}") @PreAuthorize("@vehiclePermissionGuard.allowed(authentication,'write') and @devicePermissionGuard.allowed(authentication,'write')") public ResponseEntity<Void> assign(@PathVariable Long id,@PathVariable Long deviceId){VehicleCompartment c=compartments.findById(id).orElseThrow(()->notFound("Fach nicht gefunden."));Device d=devices.findById(deviceId).orElseThrow(()->notFound("Gerät nicht gefunden."));d.setCompartment(c);d.setLocation(c.getName());devices.save(d);return ResponseEntity.noContent().build();}
 @PutMapping("/compartments/{id}/device/{deviceId}/placement") @PreAuthorize("@vehiclePermissionGuard.allowed(authentication,'write') and @devicePermissionGuard.allowed(authentication,'write')") public ResponseEntity<Void> place(@PathVariable Long id,@PathVariable Long deviceId,@RequestBody PlacementRequest r){VehicleCompartment c=compartments.findById(id).orElseThrow(()->notFound("Fach nicht gefunden."));Device d=devices.findById(deviceId).orElseThrow(()->notFound("Gerät nicht gefunden."));d.setCompartment(c);d.setLocation(c.getName());d.setPlacementX(bound(r==null?null:r.x(),0,88));d.setPlacementY(bound(r==null?null:r.y(),0,82));d.setPlacementWidth(bound(r==null?null:r.width(),12,100));d.setPlacementHeight(bound(r==null?null:r.height(),12,100));devices.save(d);return ResponseEntity.noContent().build();}
 private void apply(VehicleCompartment c,CompartmentRequest r){if(r==null||r.name()==null||r.name().isBlank())throw bad("Fachbezeichnung ist erforderlich.");String area=Optional.ofNullable(r.area()).orElse("DRIVER").toUpperCase();if(!AREAS.contains(area))throw bad("Ungültiger Fahrzeugbereich.");c.setName(trim(r.name(),80));c.setArea(area);c.setGridX(bound(r.gridX(),1,6));c.setGridY(bound(r.gridY(),1,20));c.setGridWidth(bound(r.gridWidth(),1,6));c.setGridHeight(bound(r.gridHeight(),1,4));}
 private VehicleDto dto(FireVehicle v){return new VehicleDto(v.getId(),v.getName(),v.getCallSign(),v.getNotes(),v.isFireRelevant(),compartments.findByVehicleIdOrderByGridYAscGridXAsc(v.getId()).stream().map(this::compartmentDto).toList());}
 private CompartmentDto compartmentDto(VehicleCompartment c){return new CompartmentDto(c.getId(),c.getName(),c.getArea(),c.getGridX(),c.getGridY(),c.getGridWidth(),c.getGridHeight(),devices.findByCompartmentIdAndActiveTrueOrderByNameAsc(c.getId()).stream().map(d->new VehicleDeviceDto(d.getId(),d.getName(),d.getInventoryNumber(),d.getOperationalStatus(),d.isInspectionRequired(),d.getPlacementX(),d.getPlacementY(),d.getPlacementWidth(),d.getPlacementHeight())).toList());}
 private FireVehicle find(Long id){return vehicles.findById(id).orElseThrow(()->notFound("Fahrzeug nicht gefunden."));}private int bound(Integer v,int min,int max){return Math.max(min,Math.min(max,v==null?min:v));}private String trim(String s,int max){if(s==null||s.isBlank())return null;s=s.trim();return s.substring(0,Math.min(max,s.length()));}private ResponseStatusException bad(String s){return new ResponseStatusException(HttpStatus.BAD_REQUEST,s);}private ResponseStatusException notFound(String s){return new ResponseStatusException(HttpStatus.NOT_FOUND,s);}
 public record VehicleRequest(String name,String callSign,String notes,Boolean fireRelevant){} public record CompartmentRequest(String name,String area,Integer gridX,Integer gridY,Integer gridWidth,Integer gridHeight){} public record PlacementRequest(Integer x,Integer y,Integer width,Integer height){}
 public record VehicleDeviceDto(Long id,String name,String inventoryNumber,String status,boolean inspectionRequired,int placementX,int placementY,int placementWidth,int placementHeight){} public record CompartmentDto(Long id,String name,String area,int gridX,int gridY,int gridWidth,int gridHeight,List<VehicleDeviceDto> devices){}
 public record VehicleDto(Long id,String name,String callSign,String notes,boolean fireRelevant,List<CompartmentDto> compartments){}
}
