package de.bierverein.api;
import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.server.ResponseStatusException; import org.springframework.http.HttpStatus; import java.math.BigDecimal; import java.util.*; import org.springframework.security.core.Authentication;
@Service public class MemberService {
 private final MemberRepository members; private final AppUserRepository users; private final PasswordEncoder encoder;
 public MemberService(MemberRepository m,AppUserRepository u,PasswordEncoder e){members=m;users=u;encoder=e;}
 @Transactional(readOnly=true) public List<MemberDtos.MemberResponse> all(){return members.findAll().stream().map(this::dto).toList();}
 @Transactional(readOnly=true) public MemberDtos.MemberResponse one(Long id){return dto(members.findById(id).orElseThrow());}
 @Transactional public MemberDtos.MemberResponse create(MemberDtos.MemberRequest r, Authentication auth){validate(r,null,auth); Member m=new Member(); apply(m,r); m=members.save(m); syncUser(m,r); return dto(members.save(m));}
 @Transactional public MemberDtos.MemberResponse update(Long id,MemberDtos.MemberRequest r, Authentication auth){Member m=members.findById(id).orElseThrow();validate(r,id,auth);apply(m,r);syncUser(m,r);return dto(members.save(m));}
 @Transactional public void delete(Long id, Authentication auth){Member m=members.findById(id).orElseThrow(); AppUser u=m.getUser(); if(u!=null){users.delete(u);} members.delete(m); }
 @Transactional public MemberDtos.MemberResponse balance(Long id,MemberDtos.BalanceRequest r){if(r.amount()==null||r.amount().compareTo(BigDecimal.ZERO)==0)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Betrag darf nicht 0 sein");Member m=members.findById(id).orElseThrow();m.setBalance(m.getBalance().add(r.amount()));return dto(members.save(m));}
 private void apply(Member m,MemberDtos.MemberRequest r){m.setName(r.name().trim());m.setEmail(blank(r.email()));m.setPhone(blank(r.phone()));m.setAddress(blank(r.address()));m.setActive(r.active());}
 private void validate(MemberDtos.MemberRequest r,Long id, Authentication auth){if(r.name()==null||r.name().isBlank())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Name ist erforderlich");if(Boolean.TRUE.equals(r.loginEnabled())){if(r.role()==Role.ADMIN && (auth==null || !auth.getAuthorities().stream().anyMatch(a->a.getAuthority().equals("ROLE_ADMIN"))))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Nur Administratoren dürfen die Rolle ADMIN vergeben");if(r.username()==null||r.username().isBlank())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Benutzername ist erforderlich");Optional<AppUser> u=users.findByUsername(r.username().trim());if(u.isPresent()&&(id==null||u.get().getMember()==null||!Objects.equals(u.get().getMember().getId(),id)))throw new ResponseStatusException(HttpStatus.CONFLICT,"Benutzername existiert bereits");if(r.role()==null)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Rolle ist erforderlich");}}
 private void syncUser(Member m,MemberDtos.MemberRequest r){boolean enabled=Boolean.TRUE.equals(r.loginEnabled());AppUser u=m.getUser();if(!enabled){if(u!=null)u.setEnabled(false);return;}if(u==null){u=new AppUser();u.setMember(m);if(r.password()==null||r.password().isBlank())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Für einen neuen Login ist ein Passwort erforderlich");}u.setUsername(r.username().trim());u.setRole(r.role());u.setEnabled(m.isActive());u.setRegistrationApproved(true);if(r.password()!=null&&!r.password().isBlank())u.setPasswordHash(encoder.encode(r.password()));users.save(u);m.setUser(u);}
 private MemberDtos.MemberResponse dto(Member m){AppUser u=m.getUser();return new MemberDtos.MemberResponse(m.getId(),m.getName(),m.getFirstName(),m.getLastName(),m.getEmail(),m.getPhone(),m.getAddress(),m.isActive(),m.getBalance(),u==null?null:u.getId(),u==null?null:u.getUsername(),u==null?null:u.getRole(),u!=null&&u.isEnabled());}
 private String blank(String v){return v==null||v.isBlank()?null:v.trim();}
}
